sonar.projectKey=frontend-dev-test
sonar.projectName=frontend-dev-test
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/**/*.spec.tsx
sonar.exclusions=src/**/*.stories.*,src/data/mock/**,dist/**,coverage/**,node_modules/**
sonar.coverage.exclusions=src/**/*.stories.*,src/data/mock/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
